Repository 1J3P/FarmFarm, pull requests merged in 2023-06, with the labels that each got.

#60 feat: #58 - 마이페이지 UI 구현
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
Labels: 영린🍎, Farm🌾

#63 feat: add s3
  .gitignore
  pom.xml
  src/main/java/com/example/farmfarm/Controller/S3Controller.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/java/com/example/farmfarm/Entity/FileEntity.java
  src/main/java/com/example/farmfarm/Entity/OrderDetailEntity.java
  src/main/java/com/example/farmfarm/Entity/OrderEntity.java
  src/main/java/com/example/farmfarm/Repository/EnquiryRepository.java
  src/main/java/com/example/farmfarm/Repository/FileRepository.java
  src/main/java/com/example/farmfarm/Service/FileService.java
  src/main/java/com/example/farmfarm/Service/S3Service.java
  src/main/java/com/example/farmfarm/config/S3Config.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: hyeonah🤗

#73 feat: 결제완료, 실패, 취소, 주문완료 view 구현
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/resources/static/images/categories/fruits.png
  src/main/resources/static/images/categories/vegetable.png
  src/main/resources/static/style/style.css
  src/main/webapp/WEB-INF/jsp/category/categories.jsp
  src/main/webapp/WEB-INF/jsp/common/index.jsp
  src/main/webapp/WEB-INF/jsp/common/tabbar.jsp
  src/main/webapp/WEB-INF/jsp/home/auction/auctionDetail.jsp
  src/main/webapp/WEB-INF/jsp/home/auction/auctionList.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/allFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/home.jsp
  src/main/webapp/WEB-INF/jsp/home/product/allProduct.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productGroupPurchase.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
  src/main/webapp/WEB-INF/jsp/home/product/shoppingCart.jsp
  src/main/webapp/WEB-INF/jsp/myPage/createNickname.jsp
  src/main/webapp/WEB-INF/jsp/myPage/editMyPage.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myAuctionList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myOrderList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage_enquiryList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myReviewList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/writeReview.jsp
  src/main/webapp/WEB-INF/jsp/productDetails_details.jsp
  src/main/webapp/WEB-INF/jsp/productDetails_review.jsp
  src/main/webapp/WEB-INF/jsp/search/search.jsp
  src/main/webapp/WEB-INF/jsp/search/search_not_found.jsp
  src/main/webapp/WEB-INF/jsp/shopping/orderSuccess.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentCancel.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentFail.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentSuccess.jsp
  target/classes/static/images/categories/fruits.png
  target/classes/static/images/categories/vegetable.png
  target/classes/static/style/style.css
Labels: sssssu

#72 feat: #62 - 문의사항 관련 API 구현
  src/main/java/com/example/farmfarm/Controller/EnquiryController.java
  src/main/java/com/example/farmfarm/Controller/FarmController.java
  src/main/java/com/example/farmfarm/Repository/EnquiryRepository.java
  src/main/java/com/example/farmfarm/Service/EnquiryService.java
  src/main/java/com/example/farmfarm/Service/FarmService.java
Labels: 영린🍎, Enquiry🙏

#78 feat: 주문 결제 로직 정리
  src/main/java/com/example/farmfarm/Controller/CartController.java
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/OrderDetailController.java
  src/main/java/com/example/farmfarm/Controller/PaymentController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Entity/kakaoPay/AmountEntity.java
  src/main/java/com/example/farmfarm/Service/OrderDetailService.java
  src/main/java/com/example/farmfarm/Service/OrderService.java
  src/main/java/com/example/farmfarm/Service/PaymentService.java
  target/classes/application.properties
Labels: hyeonah🤗

#83 feat: group í정리 및 수정
  src/main/java/com/example/farmfarm/Controller/AuctionController.java
  src/main/java/com/example/farmfarm/Controller/CartController.java
  src/main/java/com/example/farmfarm/Controller/FarmController.java
  src/main/java/com/example/farmfarm/Controller/GroupController.java
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/OrderDetailController.java
  src/main/java/com/example/farmfarm/Controller/PaymentController.java
  src/main/java/com/example/farmfarm/Entity/UserEntity.java
  src/main/java/com/example/farmfarm/Service/GroupService.java
  target/classes/application.properties
Labels: hyeonah🤗

#88 feat: 상품상세페이지 수정, 공동구매 페이지 연결
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productGroupPurchase.jsp
Labels: sssssu

#96 feat: 뷰 연결
  src/main/java/com/example/farmfarm/Controller/FarmController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Repository/ProductRepository.java
  src/main/resources/static/style/style.css
  src/main/webapp/WEB-INF/jsp/home/farm/allFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/home.jsp
  src/main/webapp/WEB-INF/jsp/home/product/allProduct.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
  src/main/webapp/WEB-INF/jsp/myPage/createNickname.jsp
  src/main/webapp/WEB-INF/jsp/myPage/orderList.jsp
  src/main/webapp/WEB-INF/jsp/shopping/orderSuccess.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentFail.jsp
Labels: sssssu

#103 feat: 결제 취소 실패 렌더링
  src/main/java/com/example/farmfarm/Controller/PaymentController.java
Labels: hyeonah🤗

#104 feat: 카카오로그인 페이지 넘어가게, registerFarm 넘어가게
  pom.xml
  src/main/java/com/example/farmfarm/Config/CorsConfig.java
  src/main/java/com/example/farmfarm/Config/WebSecurityConfig.java
  src/main/java/com/example/farmfarm/Controller/S3Controller.java
  src/main/java/com/example/farmfarm/Service/SchedulerService.java
  src/main/webapp/WEB-INF/jsp/common/index.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
Labels: sssssu

#108 feat: 로그인, 닉네임 설정, 홈 뷰 연결
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/java/com/example/farmfarm/Service/UserService.java
  src/main/webapp/WEB-INF/jsp/myPage/createNickname.jsp
Labels: hyeonah🤗, sssssu

#113 feat/#109 문의사항 등록
  src/main/java/com/example/farmfarm/Controller/EnquiryController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
Labels: harin💕

#117 feat: 로그인, 팜 연결
  src/main/java/com/example/farmfarm/Config/WebSecurityConfig.java
  src/main/java/com/example/farmfarm/Controller/FarmController.java
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/java/com/example/farmfarm/Service/FarmService.java
  src/main/webapp/WEB-INF/jsp/common/tabbar.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myOrderList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
Labels: hyeonah🤗

#119 feat: error.jsp 구현
  src/main/webapp/WEB-INF/jsp/common/error.jsp
Labels: sssssu

#118 feat/#116 장바구니 목록 조회
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/java/com/example/farmfarm/Entity/Cart/Item.java
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/shoppingCart.jsp
Labels: harin💕

#124 Feature/#122
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/PaymentController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/webapp/WEB-INF/jsp/common/tabbar.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
  src/main/webapp/WEB-INF/jsp/home/product/shoppingCart.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myOrderList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/orderList.jsp
Labels: hyeonah🤗

#126 feat: 주문 관련 view 수정
  src/main/resources/static/style/framework7-bundle.min.css
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
  src/main/webapp/WEB-INF/jsp/myPage/orderList.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentSuccess.jsp
Labels: sssssu

#132 공동 구매, 닉네임 오류 수정, 로그아웃 등,,
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/java/com/example/farmfarm/Entity/UserEntity.java
  src/main/java/com/example/farmfarm/Repository/GroupRepository.java
  src/main/java/com/example/farmfarm/Service/GroupService.java
  src/main/java/com/example/farmfarm/Service/UserService.java
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
Labels: hyeonah🤗

#137 feat: 상품 등록 미완성
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
Labels: sssssu

#139 feat: 상품 등록 및 product entity 수정
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Entity/ProductEntity.java
  src/main/java/com/example/farmfarm/Service/ProductService.java
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
Labels: sssssu

#140 icon, title 수정
  src/main/webapp/WEB-INF/jsp/category/categories.jsp
  src/main/webapp/WEB-INF/jsp/common/error.jsp
  src/main/webapp/WEB-INF/jsp/common/index.jsp
  src/main/webapp/WEB-INF/jsp/common/tabbar.jsp
  src/main/webapp/WEB-INF/jsp/home/auction/auctionDetail.jsp
  src/main/webapp/WEB-INF/jsp/home/auction/auctionList.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/allFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/home.jsp
  src/main/webapp/WEB-INF/jsp/home/product/allProduct.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productGroupPurchase.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
  src/main/webapp/WEB-INF/jsp/home/product/shoppingCart.jsp
  src/main/webapp/WEB-INF/jsp/myPage/createNickname.jsp
  src/main/webapp/WEB-INF/jsp/myPage/editMyPage.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myAuctionList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myEnquiryList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myReviewList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/orderList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/writeReview.jsp
  src/main/webapp/WEB-INF/jsp/search/search.jsp
  src/main/webapp/WEB-INF/jsp/search/search_not_found.jsp
  src/main/webapp/WEB-INF/jsp/shopping/orderSuccess.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentCancel.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentFail.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentSuccess.jsp
Labels: hyeonah🤗

#143 auction 폼! 결제 연결까지 완료!!!!!
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/webapp/WEB-INF/jsp/home/auction/auctionDetail.jsp
  src/main/webapp/WEB-INF/jsp/myPage/editMyPage.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentSuccess.jsp
Labels: hyeonah🤗

#144 회원정보 수정, 경매 내역, 주문 내역 등 수정
  README.md
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/java/com/example/farmfarm/Controller/OrderController.java
  src/main/java/com/example/farmfarm/Controller/UserController.java
  src/main/java/com/example/farmfarm/Entity/OrderEntity.java
  src/main/java/com/example/farmfarm/Repository/OrderRepository.java
  src/main/java/com/example/farmfarm/Service/OrderService.java
  src/main/java/com/example/farmfarm/Service/UserService.java
  src/main/webapp/WEB-INF/jsp/myPage/editMyPage.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myAuctionList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myOrderList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
Labels: hyeonah🤗

#145 주문 내역, 경매 내역 살짝 수정
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myAuctionList.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentSuccess.jsp
Labels: hyeonah🤗

#150 홈 화면 반 완성
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/webapp/WEB-INF/jsp/home/home.jsp
Labels: hyeonah🤗

#151 feat: 배송지 입력, 프로필 수정, 결제 성공 view 수정
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
  src/main/webapp/WEB-INF/jsp/myPage/editMyPage.jsp
  src/main/webapp/WEB-INF/jsp/shopping/paymentSuccess.jsp
Labels: sssssu

#154 feat: home.jsp 경매 시간 띄움
  src/main/resources/static/style/style.css
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/home.jsp
Labels: sssssu

#161 농장 삭제 구현
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/java/com/example/farmfarm/Repository/FarmRepository.java
  src/main/java/com/example/farmfarm/Service/FarmService.java
Labels: hyeonah🤗

#162 feat: view 이상한거 수정
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productShippingAddress.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myAuctionList.jsp
Labels: sssssu

#163 농장 ì삭제 살짝 수정, 상품 삭제 완료
  src/main/java/com/example/farmfarm/Controller/ProductController.java
  src/main/java/com/example/farmfarm/Entity/ProductEntity.java
  src/main/java/com/example/farmfarm/Repository/ProductRepository.java
  src/main/java/com/example/farmfarm/Service/ProductService.java
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
Labels: hyeonah🤗

#164 판매 상품 조회 이미지 수정
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
Labels: hyeonah🤗

#165 리뷰 마지막 수정!
  src/main/java/com/example/farmfarm/Controller/FarmController.java
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/java/com/example/farmfarm/Service/FarmService.java
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/shoppingCart.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
  src/main/webapp/WEB-INF/jsp/search/search.jsp
Labels: hyeonah🤗
