Repository 1J3P/FarmFarm, pull requests merged in 2023-08, with the labels that each got.

#168 feat: 농장 분기 처리 jsp 수정
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
Labels: sssssu

#174 feat: 마이페이지 jsp 수정, 상품 없을때 문구 처리
  src/main/resources/static/style/framework7-bundle.min.css
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/allProduct.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myAuctionList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myEnquiryList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myOrderList.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myReviewList.jsp
Labels: sssssu

#176 fix: 마이페이지 오류 수정 및 input 비었을때 처리
  src/main/java/com/example/farmfarm/Controller/FarmController.java
  src/main/java/com/example/farmfarm/Controller/HomeController.java
  src/main/webapp/WEB-INF/jsp/home/farm/farmDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/farm/registerFarm.jsp
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
  src/main/webapp/WEB-INF/jsp/myPage/createNickname.jsp
  src/main/webapp/WEB-INF/jsp/myPage/editMyPage.jsp
  src/main/webapp/WEB-INF/jsp/myPage/myPage.jsp
Labels: 영린🍎

#179 feat: fix error of registerProduct
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
  src/main/webapp/WEB-INF/jsp/home/product/registerProduct.jsp
Labels: hyeonah🤗

#180 feat: 상품 슬라이드 구현
  src/main/resources/static/style/style.css
  src/main/webapp/WEB-INF/jsp/home/product/productDetails.jsp
Labels: sssssu
